### ISSUE TITLE
Add dark mode

### ISSUE THREAD

**Issue by peldas** [HIllya51/LunaHook#147]
This is the only program on my PC which is blinding white and it's quite painful to look at while reading at night. Please add a toggleable dark mode in the settings.

**Comment by HIllya51** [comment]
use [LunaTranslator](https://github.com/HIllya51/LunaTranslator) instead. 
This program is only the core module of LunaTranslator, and I don't recommand anyone to direct use it.

**Comment by peldas** [comment]
I tried downloading LunaTranslator; while it's quite nice and has a dark mode and extra UI languages, it's full of a _lot_ of crap that you won't find most Japanese learners using. We mainly just need the functionality in LunaHook and don't use translations or any of the other extra stuff (and I'm speaking for thousands of people who were previously using Textractor for this purpose). I don't see anyone in the community changing to use LunaTranslator. I suppose I will just put up with the white UI until I can be bothered to recompile it with dark mode myself.

**Comment by HIllya51** [comment]
It's just that you don't know how to use it. In our community, many people are using A to learn Japanese.
Why LunaTranslator has too much nonsense is because thousands of Japanese learners keep asking me to provide more functions for its initial version ( which is similar to LunaHook now ) and then it became what it likes now. 
So I have no interest in going through this same path again.

**Comment by HIllya51** [comment]
LunaHook will only be a text extractor kernel, not a more complex application.
If you want a compromise between LunaHook and LuanTranslator, you can use LunaHost32.dll/LunaHostCLI32.exe to easily build your own software, which is why I provide them

**Comment by HIllya51** [comment]
And there is another important reason, LunaHook must maintain compatibility with Windows XP system. If you want to implement what you said, it will force LunaHook to give up support for some games that can only run on Windows XP system, which will make many people unhappy.

**Comment by HIllya51** [comment]
In order to run on XP, its UI is written in pure win32. So it is impossible to implement dark mode by simple modification.
So I suggest you implement a UI to call the LunaHook's kernel, which is very easy to do. I can also provide you with a reference: https://github.com/HIllya51/LunaTranslator/blob/main/LunaTranslator/LunaTranslator/textsource/texthook.py.
