### ISSUE TITLE
this game is based on flash, so I guess that's why luna translator crash(on wine)

### ISSUE THREAD

**Issue by asukaminato0721** [HIllya51/LunaHook#18]
### vndb id

r38754

### Game resource 游戏资源

<https://1drv.ms/u/c/ef2183d7ce6988de/EVTazrFsPbVHjH68pyfypI0BIRog8TNDktIVnDZrkyvvYQ>

download from <https://sukebei.nyaa.si/view/1895077>

when I hook on this game, luna translator crashes.

**Comment by HIllya51** [comment]
don’t know why can’t download...

![屏幕截图 2024-04-24 191033](https://github.com/HIllya51/LunaHook/assets/101191390/3be63621-4880-431c-81b3-543ce2ac8ee1)

**Comment by HIllya51** [comment]
I don't have a linux computer, so I can't test on wine.

**Comment by HIllya51** [comment]
tested on ubuntu22lts, no any error happeded
![屏幕截图 2024-04-25 144043](https://github.com/HIllya51/LunaHook/assets/101191390/6c2dbb03-10e6-41de-95d1-a53e2961b6e6)
![屏幕截图 2024-04-25 144219](https://github.com/HIllya51/LunaHook/assets/101191390/da6dc288-a4a3-4a66-ab8e-8477d791c71e)

**Comment by HIllya51** [comment]
LunaTranslator contains too many modules, making it difficult to debug on Wine. 
I noticed that the default Aria font for LunaHook cannot be displayed properly on Linux, so I just added font settings for LunaHook to make it work better on Linux. So if the program still crashes, please use LunaHook instead of LunaTranslator's Hook mode to extract game's text.
