### ISSUE TITLE
Troyan Trojan:Win32/Bearfoos.A!ml detected in the newest release 3.2.3

### ISSUE THREAD

**Issue by Baten84** [HIllya51/LunaHook#38]
### Version 程序版本

3.2.3

### Related screenshot (optional) 相关截图（可选）

![image](https://github.com/HIllya51/LunaHook/assets/121767249/e220b54c-278f-440c-bad7-25c936e5f4e2)
![image](https://github.com/HIllya51/LunaHook/assets/121767249/de0183f8-bd41-4bf9-b107-3edf4a668f7b)

### Reproduction steps 复现步骤

Windows Security recognizes LunaHook32.dll as Trojan:Win32/Bearfoos.A!ml and LunaHostCLI32.exe as Program:Win32/Wacapew.C!ml.

**Comment by HIllya51** [comment]
The release is automatically build by Github Actions since https://github.com/HIllya51/LunaHook/commit/44473219644bc1ead92b2a0b1f3722c85b1b8bec . So unless GitHub's server is poisoned, the software is 100% secure. You can obtain all CI build history at [Actions](https://github.com/HIllya51/LunaHook/actions)
