### ISSUE TITLE
[Feature Request] Manual Hook Search

### ISSUE THREAD

**Issue by rampaa** [HIllya51/LunaHook#4]
It would be quite convenient if LunaHook allowed us to search for hooks manually like Textractor does with the "Search for hooks" button.

**Comment by HIllya51** [comment]
Ok, I have already added this function same to Textractor.
But actually , I promise you to use LunaTranslator to do Hook Search, because LunaTranslator provide some extra Hook Search methods to better find the hooks.

<img width="658" alt="屏幕截图 2024-03-28 193100" src="https://github.com/HIllya51/LunaHook/assets/101191390/f3b47dcd-d883-4741-bbea-d4caf6c753c0">

**Comment by rampaa** [comment]
> Ok, I have already added this function similar to Textractor.

Thanks a lot!

![image](https://github.com/HIllya51/LunaHook/assets/25622653/094bbf35-215c-4515-8a0d-0eb1b70524cf)

Probably the first button should be named "Start hook search". And probably the Settings button should function even LunaHook is not attached to any game (currently pressing the Settings button does nothing when LunaHook is not attached to any game)

> use LunaTranslator to do Hook Search, because LunaTranslator provide some extra Hook Search methods to better find the hooks

Thanks for the suggestion but as I've previously mentioned I think LunaHook fits the bill better for my needs. A quick question though, is there anything inherently special about those other extra hook search methods that would make it hard to port over LunaHook? Ideally speaking I'd love them to be present in LunaHook.

In any case, thank you so much for the prompt responses and releases. With those changes I believe I can switch from Textractor to LunaHook finally.

**Comment by HIllya51** [comment]
> Probably the first button should be named "Start hook search". And probably the "Settings" button should function even if LunaHook is not attached to any game (currently pressing the Settings button does nothing when LunaHook is not attached to any game)

these three buttons and their functions are complete same to Textractor.
<img width="264" alt="屏幕截图 2024-03-29 024709" src="https://github.com/HIllya51/LunaHook/assets/101191390/6b537595-9358-42bc-abb1-3d679c45a6bd">

Actually, the "Search for Specific text" is Search by default setting, and "Settings" is Search by user setting. So the "Settings" is impossible to work when not attached to a game.

> Thanks for the suggestion but as I've previously mentioned I think LunaHook fits the bill better for my needs. A quick question though, is there anything inherently special about those other extra hook search methods that would make it hard to port over LunaHook? Ideally speaking I'd love them to be present in LunaHook.

Use the pattern to Search hook usually can't find many hooks and usually cause game to crush. So I develop the other Search method "Function alignment" and "function call" which often perform better than search by pattern.
I'm probably not going to add this two additional search methods, mainly because it is too hard to use win32 to develop the GUI😂 And in fact, Search by pattern is enough in most cases. Even if can't find a suitable hook, the best way is to request me to find and I will add the new hook in LunaHook.

**Comment by HIllya51** [comment]
> Figured as such but the first two buttons have the same name in LunaHook v2.5.0, probably a localization oversight.

What? These three buttons' function and there name are totally same to Textractor, where is the oversight?

> Oh, I didn't know about that. I though the "Settings" was a global thing, since Textractor does open the hook search settings when "Settings" button is clicked, even when it is not attached to any game.

In fact, in Textractor, no matter how you modify it, every time you reopen it, it will be restored to the default value and no settings will be saved.

**Comment by rampaa** [comment]
> What? These three buttons' function and there name are totally same to Textractor, where is the oversight?

![image](https://github.com/HIllya51/LunaHook/assets/25622653/a1577204-c3ae-467c-bf34-d9d2c66bcf52)

See the screenshot above. Notice how both of the first two button are named "Search for specific text".

![image](https://github.com/HIllya51/LunaHook/assets/25622653/6db862ff-616c-40ca-b32c-8f0033bb411e)

See the screenshot above. Notice how the first button is named "Start hook search" and not "Search for specific text".

Textractor buttons: "Start hook search", "Search for specific text", "Settings"
LunaHook buttons: "Search for specific text", "Search for specific text", "Settings"

**Comment by HIllya51** [comment]
Haha, These words are so similar, I misread them

**Comment by HIllya51** [comment]
fixed
